const Combos = [
    {
        id: 1,
        name: 'BABY SHARK SINGLE COMBO - 195.000 đ',
        content1: '1 ly Baby Shark + 1 nước siêu lớn',
        content2: 'Mua thêm một bắp ngọt lớn chỉ 29k',
        content3: 'Nhận trong ngày xem phim',
        content4: 'Mẫu ly phụ thuộc vào số lượng từng rạp',
    },
    {
        id: 2,
        name: 'BABY SHARK SINGLE COMBO - 195.000 đ',
        content1: '1 ly Baby Shark + 1 nước siêu lớn',
        content2: 'Mua thêm một bắp ngọt lớn chỉ 29k',
        content3: 'Nhận trong ngày xem phim',
        content4: 'Mẫu ly phụ thuộc vào số lượng từng rạp',
    },
    {
        id: 3,
        name: 'BABY SHARK SINGLE COMBO - 195.000 đ',
        content1: '1 ly Baby Shark + 1 nước siêu lớn',
        content2: 'Mua thêm một bắp ngọt lớn chỉ 29k',
        content3: 'Nhận trong ngày xem phim',
        content4: 'Mẫu ly phụ thuộc vào số lượng từng rạp',
    },
    {
        id: 4,
        name: 'BABY SHARK SINGLE COMBO - 195.000 đ',
        content1: '1 ly Baby Shark + 1 nước siêu lớn',
        content2: 'Mua thêm một bắp ngọt lớn chỉ 29k',
        content3: 'Nhận trong ngày xem phim',
        content4: 'Mẫu ly phụ thuộc vào số lượng từng rạp',
    },
    {
        id: 5,
        name: 'BABY SHARK SINGLE COMBO - 195.000 đ',
        conten1: '1 ly Baby Shark + 1 nước siêu lớn',
        content2: 'Mua thêm một bắp ngọt lớn chỉ 29k',
        content3: 'Nhận trong ngày xem phim',
        content4: 'Mẫu ly phụ thuộc vào số lượng từng rạp',
    },
    {
        id: 6,
        name: 'BABY SHARK SINGLE COMBO - 195.000 đ',
        content1: '1 ly Baby Shark + 1 nước siêu lớn',
        content2: 'Mua thêm một bắp ngọt lớn chỉ 29k',
        content3: 'Nhận trong ngày xem phim',
        content4: 'Mẫu ly phụ thuộc vào số lượng từng rạp',
    },
];
export default Combos;
