const { default: HomeImage } = require('./HomeImage');

const SelectMoviesPresent = [
    {
        id: 1,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[0].image,
    },
    {
        id: 2,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[0].image,
    },
    {
        id: 3,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[0].image,
    },
    {
        id: 4,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[0].image,
    },
    {
        id: 5,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[0].image,
    },
    {
        id: 6,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[0].image,
    },
    {
        id: 7,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[0].image,
    },
    {
        id: 8,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[0].image,
    },
    {
        id: 9,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[0].image,
    },
    {
        id: 10,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[0].image,
    },
    {
        id: 11,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[0].image,
    },
    {
        id: 12,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[0].image,
    },
    {
        id: 13,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[0].image,
    },
    {
        id: 14,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[0].image,
    },
    {
        id: 15,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[0].image,
    },
];

const SelectMoviesFuture = [
    {
        id: 1,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[1].image,
    },
    {
        id: 2,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[1].image,
    },
    {
        id: 3,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[1].image,
    },
    {
        id: 4,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[1].image,
    },
    {
        id: 5,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[1].image,
    },
    {
        id: 6,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[1].image,
    },
    {
        id: 7,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[1].image,
    },
    {
        id: 8,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[1].image,
    },
    {
        id: 9,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[1].image,
    },
    {
        id: 10,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[1].image,
    },
    {
        id: 11,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[1].image,
    },
    {
        id: 12,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[1].image,
    },
    {
        id: 13,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[1].image,
    },
    {
        id: 14,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[1].image,
    },
    {
        id: 15,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[1].image,
    },
];

const SelectMoviesSpecial = [
    {
        id: 1,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[2].image,
    },
    {
        id: 2,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[2].image,
    },
    {
        id: 3,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[2].image,
    },
    {
        id: 4,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[2].image,
    },
    {
        id: 5,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[2].image,
    },
    {
        id: 6,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[2].image,
    },
    {
        id: 7,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[2].image,
    },
    {
        id: 8,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[2].image,
    },
    {
        id: 9,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[2].image,
    },
    {
        id: 10,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[2].image,
    },
    {
        id: 11,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[2].image,
    },
    {
        id: 12,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[2].image,
    },
    {
        id: 13,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[2].image,
    },
    {
        id: 14,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[2].image,
    },
    {
        id: 15,
        name: 'Spider-Man: No Way Home',
        time: '120 phút',
        premiere: '15/09/2023',
        category: 'Adventure/Superhero',
        image: HomeImage[2].image,
    },
];

export { SelectMoviesPresent, SelectMoviesFuture, SelectMoviesSpecial };
